server {
    listen       80;
    listen  [::]:80;
    server_name  localhost;

    location / {
        root   /usr/share/nginx/html/website;
        index  index.html;

        if ($request_uri ~ ^/(.*)\.html(\?|$)) {
            return 302 /$1$is_args$args;
        }
        try_files $uri $uri.html $uri/ =404;

        # Disable caching with HTTP headers
        add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0";
        add_header Pragma "no-cache";
        add_header Expires 0;
    }

    error_page 403 /errors/403.html;
    error_page 404 /errors/404.html;
    error_page 500 /errors/500.html;
    error_page 503 /errors/503.html;
}

# cdn website
server {
    listen       82;
    listen  [::]:82;
    server_name  localhost;
    absolute_redirect off;

    location / {
        root   /usr/share/nginx/html/cdn;
        deny all;
    }

    location /website {
        autoindex on;
        root   /usr/share/nginx/html/cdn;
        allow all;

        # Single trusted origin
        add_header 'Access-Control-Allow-Origin' '*' always;
        add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, DELETE, OPTIONS' always;
        add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization' always;
        add_header 'Vary' 'Origin' always;

        if ($request_method = 'OPTIONS') {
            add_header 'Access-Control-Max-Age' 86400;
            add_header 'Content-Type' 'text/plain; charset=utf-8';
            add_header 'Content-Length' 0;
            return 204;
        } 
    }
}