server {
    listen       80;
    listen  [::]:80;
    server_name  localhost;

    location / {
        root   /usr/share/nginx/html;
        index  index.html;

        # if ($request_uri ~ ^/(.*)\.html(\?|$)) {
        #     return 302 /$1$is_args$args;
        # }
        # try_files $uri $uri.html $uri/ =404;
    }

    location /gallery {
        root   /usr/share/nginx/html;
        index  gallery.html;
    }

    location /website {
        root   /usr/share/nginx/html;
        index  website.html;
    }


    error_page  404              /errors/404.html;

    #redirect server error pages to the static page /errors/50x.html
    
    error_page   500 503  /errors/50x.html;
    location = /errors/50x.html {
        root   /usr/share/nginx/html/errors;
    }
}

